### ISSUE TITLE
[Feature suggestion] Would it be interesting to add a optional key field ?

### ISSUE THREAD

**Issue by Lolozendev** [kgretzky/evilginx2#1039]
Wouldn't it be interesting to add a 'OR' type of search instead of 'AND' (optional key fields) , for example let's say my credentials fields looks like this in my phislet:

```
credentials:
  username:
    key: 'login'
    search: '(.*)'
    type: 'post'
  password:
    key: 'password'
    search: '(.*)'
    type: 'post'
```

but sometime my user has a 2fa or a pin I wanna capture and that depends if he has enabled the 2fa/pin feature. maybe it could be interesting to add some keys/field that can be optionality present and captured if they exist

```
credentials:
  username:
    key: 'login'
    search: '(.*)'
    type: 'post'
  password:
    key: 'password'
    search: '(.*)'
    type: 'post'
  custom:
    - key: 'otp' #present only if the user as the 2fa enabled
      search: '(.*)'
      type: 'post'
      optional: True # specify that on request this argument maybe not exist and captures it only if it does
```

credentials wouldn't be the only field that would benefits from this feature.
