### ISSUE TITLE
Credentials type is not properly handled

### ISSUE THREAD

**Issue by n0whereman** [kgretzky/evilginx2#112]
Hello Kuba,
thank for all the phish (pun intended :) )..
While playing with the tool, I stumbled upon a bug. The new format of phislets requires users to create credentials section as follows:

```
credentials:
  username:
    key: ''
    search: '"username":"([^"]*)'
    type: 'json'
  password:
    key: ''
    search: '"password":"([^"]*)'
    type: 'json'

```
Although I was pretty convinced that my search regexp would match the values from JSON post, no credentials popped in the console application. Therefore, I quickly skimmed through source code and probably identified the problematic behaviour. The regexp seems to be good, but when yaml is LoadFromFile and unmarshall to the object, there seems to be no assignment to _p.username.tp_ and _p.password.tp_  except the following one, which was supposed set Type "post" as default. 
phislet.go
```
if p.username.tp == "" {
   p.username.tp = "post"
}
if p.password.tp == "" {
  p.password.tp = "post"
}
```
Hence, both _p.username.tp_ and _p.password.tp_ are always "post" type. Thus in http_proxy.go the if statments 
`if pl.password.tp == "json"` and if `pl.username.tp == "json"` will never be true. 
Please, check my assumptions, if I am right, I could provide you with a fix but that's rather simple one. 

Yours truly,
Martin
