### ISSUE TITLE
Collection of auth tokens of multiple subdomains not possible

### ISSUE THREAD

**Issue by edermi** [kgretzky/evilginx2#46]
Today I tried to collect auth tokens. The service that I'm using has cookies for the parent and a subdomain that keep authentication information, but unfortunately I was unable to fetch them using evilginx2. 

```
auth_tokens:
  - domain: '.service.net'
    keys: ['token1', 'token2']
  - domain: 'sub.service.net'
    keys: ['subtoken1', 'subtoken2']
```
When commenting out the second entry, everything works as expected, but I'm missing relevant cookies that are required for impersonating a session. I also tried:
```
auth_tokens:
  - {domain: '.service.net', keys: ['token1', 'token2']}
  - {domain: 'sub.service.net', keys: ['subtoken1', 'subtoken2']}
```
but I guess that's just another way to write this and doesn't make a difference since your parser should anyway give you an equivalent abstraction.

Unfortunately, it's not a service where you may simply register a free account for testing, but I guess this is a simple bug that just has been overlooked and I can help you testing if required.
