### ISSUE TITLE
Does not load the website if on specific port

### ISSUE THREAD

**Issue by pr0t0nus3rxyz** [kgretzky/evilginx2#537]
I have created a phishlet for custom website which is in format http://website:1337 . So i specify the port in the phishlets both proxy_hosts and login but no luck. Also i tried putting it in path: ':1337' but still it doesnt loads the phishing url. I tried modifying the core phishlets.go file and compiling it again after making some changes still it redirects to youtube.com. 

Can anyone fix this to make support for custom urls with ports.

**Comment by Hackndo** [comment]
I tried and [added this on my fork](https://github.com/Hackndo/evilginx2/commit/90be8d157be8f8490f80eaca636011ece27fbb9c), but there will be some testing needed before I ask for a PR, as I'm not sure if it's safe, or if it breaks some stuff.
It worked with my tests.

Note the `port` in `proxy_hosts` and in `login`

```yaml
author: '@pixis'
min_ver: '2.3.0'
proxy_hosts:
  - {phish_sub: '', orig_sub: '', domain: 'mywebsite.com', port: 1443, session: true, is_landing: true}

sub_filters: []

auth_tokens:
  - domain: 'mywebsite.com'
    keys: ['LOGINID']
credentials:
  username:
    key: 'login'
    search: '(.*)'
    type: 'post'
  password:
    key: 'password'
    search: '(.*)'
    type: 'post'

login:
  domain: 'mywebsite.com'
  port: 1443
  path: '/'
```
