### ISSUE TITLE
[bug] incorrect domain substitution with certain yaml configs

### ISSUE THREAD

**Issue by audibleblink** [kgretzky/evilginx2#60]
Somewhat related to #57 , the wrong hostname gets substituted with the following configurations.
```yaml
proxy_hosts:
  - {phish_sub: 'ssl', orig_sub: 'ssl', domain: 'abc.com', session: false, is_landing: true}
  - {phish_sub: 'ssl', orig_sub: 'ssl', domain: 'xyz.com', session: false, is_landing: false}
sub_filters:
  - {hostname: 'oath.abc.com', sub: 'ssl', domain: 'xyz.com', search: '{hostname}', replace: '{hostname}', mimes: ['...']}
```

The requests should be going to `https://ssl.xyz.com.phishdomain.com`, but instead show in DevTools as `https://ssl.abc.com.phishdomain.com`.

My current workaround is to hardcode my phish domain into the phishlet config, which prevents me from sharing the phishlet.

```yaml
sub_filters:
   -  {hostname: 'oath.abc.com', sub: 'ssl', domain: 'xyz.com', search: '{hostname}', replace: '{subdomain}.xyz.com.phishdomain.com', mimes: ['...']}
```
